org.gradle.jvmargs=-Xmx4G

minecraft_version=1.21.1
yarn_version=1.21.1+build.3

archives_base_name=CobblemonTrainers
mod_version=1.1.12-port
maven_group=com.selfdot

#architectury_version=9.2.14
architectury_version=13.0.6

fabric_loader_version=0.16.9
fabric_api_version=0.114.0+1.21.1
fabric_permissions_api_version=0.3.1

forge_version=1.21.1-52.0.40
kff_version=4.10.0

luckperms_version=5.4
cobblemon_version=1.6.0
selfdot_modlibs_version=4.2.3
lombok_version=1.18.36
kotlin_stdlib_version=2.0.21
